/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Felipe Junior e Jhonathan Freitas
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    /**
     * Compartilha a mesma biblioteca entre as telas para que livros,
     * membros e empréstimos usem os mesmos registros durante a execução.
     */
    private final Biblioteca biblioteca = new Biblioteca();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        setSize(650, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbLivros = new javax.swing.JButton();
        jbMembros = new javax.swing.JButton();
        jbEmprestimos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Biblioteca");
        setPreferredSize(new java.awt.Dimension(600, 300));

        jbLivros.setText("Gerenciamento de Livros");
        jbLivros.addActionListener(this::jbLivrosActionPerformed);

        jbMembros.setText("Gerenciamento de Membros");
        jbMembros.addActionListener(this::jbMembrosActionPerformed);

        jbEmprestimos.setText("Gerenciamento de Empréstimos");
        jbEmprestimos.addActionListener(this::jbEmprestimosActionPerformed);

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Sistema de Biblioteca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jbLivros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbMembros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEmprestimos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLivros)
                    .addComponent(jbMembros)
                    .addComponent(jbEmprestimos))
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLivrosActionPerformed
        // TODO add your handling code here:
        // Linkar o botão a tela de livro
        new TelaLivros(biblioteca).setVisible(true);
    }//GEN-LAST:event_jbLivrosActionPerformed

    private void jbMembrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMembrosActionPerformed
        // TODO add your handling code here:
        // Linkar o botão a tela de membro
        new TelaMembros(biblioteca).setVisible(true);
    }//GEN-LAST:event_jbMembrosActionPerformed

    private void jbEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEmprestimosActionPerformed
        // TODO add your handling code here:
        // Linkar o botão a tela de emprestimos
        new TelaEmprestimos(biblioteca).setVisible(true);
    }//GEN-LAST:event_jbEmprestimosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbEmprestimos;
    private javax.swing.JButton jbLivros;
    private javax.swing.JButton jbMembros;
    // End of variables declaration//GEN-END:variables
}
