/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Felipe Junior e Jhonathan Freitas
 */
public class TelaLivros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLivros.class.getName());
    private final Biblioteca biblioteca;
    /**
     * Creates new form TelaLivros
     */
    public TelaLivros() {
        this(new Biblioteca());
    }
    
    public TelaLivros(Biblioteca biblioteca) {
        this.biblioteca = biblioteca;
        initComponents();
        // Lê os livros armazenados no modelo Biblioteca e atualiza a tabela da tela.
        atualizarTabela();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTitulo = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jlAutor = new javax.swing.JLabel();
        jtfAutor = new javax.swing.JTextField();
        jlAno = new javax.swing.JLabel();
        jtfAno = new javax.swing.JTextField();
        jlISBN = new javax.swing.JLabel();
        jtfIsbn = new javax.swing.JTextField();
        jbAdicionar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLivros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Livros");

        jlTitulo.setText("Título:");

        jlAutor.setText("Autor:");

        jlAno.setText("Ano:");

        jtfAno.addActionListener(this::jtfAnoActionPerformed);

        jlISBN.setText("ISBN:");

        jtfIsbn.addActionListener(this::jtfIsbnActionPerformed);

        jbAdicionar.setText("Adicionar livro");
        jbAdicionar.addActionListener(this::jbAdicionarActionPerformed);

        jbEditar.setText("Editar livro");
        jbEditar.addActionListener(this::jbEditarActionPerformed);

        jbRemover.setText("Remover livro");
        jbRemover.addActionListener(this::jbRemoverActionPerformed);

        jtLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLivros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfAno))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfIsbn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbEditar)
                        .addGap(28, 28, 28)
                        .addComponent(jbRemover))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfAutor)
                            .addComponent(jtfTitulo))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAno, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfIsbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdicionar)
                    .addComponent(jbEditar)
                    .addComponent(jbRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnoActionPerformed

    private void jtfIsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIsbnActionPerformed
    
    // Valida os campos, cria um Livro e o adiciona à Biblioteca.
    private void jbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarActionPerformed
        // TODO add your handling code here:
        String titulo = jtfTitulo.getText().trim();
        String autor = jtfAutor.getText().trim();
        String textoAno = jtfAno.getText().trim();
        String isbn = jtfIsbn.getText().trim();

        if (titulo.isEmpty() || autor.isEmpty() || textoAno.isEmpty() || isbn.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }

        int ano;
        try {
            ano = Integer.parseInt(textoAno);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "O ano deve ser um número.");
            return;
        }

        if (ano < 1 || ano > java.time.LocalDate.now().getYear()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Informe um ano válido.");
            return;
        }

        int proximoId = 1;
        for (Livro livro : biblioteca.getLivros()) {
            if (livro.getIsbn().equalsIgnoreCase(isbn)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Esse ISBN já está cadastrado.");
                return;
            }
            proximoId = Math.max(proximoId, livro.getId() + 1);
        }

        Livro livro = new Livro(proximoId, titulo, autor, isbn);
        livro.setAno(ano);
        biblioteca.adicionarLivro(livro);

        atualizarTabela();
        jtfTitulo.setText("");
        jtfAutor.setText("");
        jtfAno.setText("");
        jtfIsbn.setText("");

        javax.swing.JOptionPane.showMessageDialog(this, "Livro adicionado com sucesso.");
    }//GEN-LAST:event_jbAdicionarActionPerformed
    
    // Atualiza na Biblioteca os dados do livro selecionado na tabela.
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        int linha = jtLivros.getSelectedRow();
        if (linha < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um livro na tabela.");
            return;
        }

        int linhaModelo = jtLivros.convertRowIndexToModel(linha);
        int id = (int) jtLivros.getModel().getValueAt(linhaModelo, 0);

        String titulo = jtfTitulo.getText().trim();
        String autor = jtfAutor.getText().trim();
        String textoAno = jtfAno.getText().trim();
        String isbn = jtfIsbn.getText().trim();

        if (titulo.isEmpty() || autor.isEmpty() || textoAno.isEmpty() || isbn.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }

        int ano;
        try {
            ano = Integer.parseInt(textoAno);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "O ano deve ser um número.");
            return;
        }

        if (ano < 1 || ano > java.time.LocalDate.now().getYear()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Informe um ano válido.");
            return;
        }

        for (Livro outro : biblioteca.getLivros()) {
            if (outro.getId() != id && outro.getIsbn().equalsIgnoreCase(isbn)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Esse ISBN já pertence a outro livro.");
                return;
            }
        }

        biblioteca.editarLivro(id, titulo, autor, isbn);
        Livro livro = biblioteca.buscarLivroPorId(id);
        livro.setAno(ano);

        atualizarTabela();
        jtfTitulo.setText("");
        jtfAutor.setText("");
        jtfAno.setText("");
        jtfIsbn.setText("");

        javax.swing.JOptionPane.showMessageDialog(this, "Livro atualizado com sucesso.");
    }//GEN-LAST:event_jbEditarActionPerformed
    
    // Verifica se o livro pode ser removido e o exclui da Biblioteca.
    private void jbRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRemoverActionPerformed
        // TODO add your handling code here:
        int linha = jtLivros.getSelectedRow();
        if (linha < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um livro na tabela.");
            return;
        }

        int linhaModelo = jtLivros.convertRowIndexToModel(linha);
        int id = (int) jtLivros.getModel().getValueAt(linhaModelo, 0);

        for (Emprestimo emprestimo : biblioteca.getEmprestimos()) {
            if (emprestimo.isAtivo() && emprestimo.getLivro().getId() == id) {
                javax.swing.JOptionPane.showMessageDialog(
                    this, "Não é possível remover um livro com empréstimo ativo."
                );
                return;
            }
        }

        int resposta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Deseja remover o livro selecionado?",
            "Confirmar remoção",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (resposta != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        biblioteca.removerLivro(id);
        atualizarTabela();
        jtfTitulo.setText("");
        jtfAutor.setText("");
        jtfAno.setText("");
        jtfIsbn.setText("");
    }//GEN-LAST:event_jbRemoverActionPerformed
    
    // Ao clicar em uma linha da tabela, carrega os dados do livro nos campos
    // do formulário para permitir edição ou remoção.
    private void jtLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLivrosMouseClicked
        // TODO add your handling code here:
        int linha = jtLivros.getSelectedRow();

        if (linha < 0) {
            return;
        }

        int linhaModelo = jtLivros.convertRowIndexToModel(linha);
        int id = (int) jtLivros.getModel().getValueAt(linhaModelo, 0);
        Livro livro = biblioteca.buscarLivroPorId(id);

        if (livro != null) {
            jtfTitulo.setText(livro.getTitulo());
            jtfAutor.setText(livro.getAutor());
            jtfAno.setText(String.valueOf(livro.getAno()));
            jtfIsbn.setText(livro.getIsbn());
        }
    }//GEN-LAST:event_jtLivrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLivros().setVisible(true));
    }
    
    /**
    * Atualiza a JTable com os registros armazenados na Biblioteca.
    * Cria as colunas e adiciona uma linha para cada registro do modelo.
    */
    private void atualizarTabela() {
    javax.swing.table.DefaultTableModel modelo =
        new javax.swing.table.DefaultTableModel(
            new Object[]{"ID", "Título", "Autor", "Ano", "ISBN", "Disponível"}, 0
        ) {
            @Override
            public boolean isCellEditable(int linha, int coluna) {
                return false;
            }
        };

    for (Livro livro : biblioteca.getLivros()) {
        modelo.addRow(new Object[]{
            livro.getId(),
            livro.getTitulo(),
            livro.getAutor(),
            livro.getAno(),
            livro.getIsbn(),
            livro.getDisponivel() ? "Sim" : "Não"
        });
    }

    jtLivros.setModel(modelo);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAdicionar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbRemover;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlISBN;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTable jtLivros;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfAutor;
    private javax.swing.JTextField jtfIsbn;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables
}
