/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Felipe Junior e Jhonathan Freitas
 */
public class TelaMembros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMembros.class.getName());
    private final Biblioteca biblioteca;
    /**
     * Creates new form TelaMembros
     */
    public TelaMembros() {
        this(new Biblioteca());
    }

    public TelaMembros(Biblioteca biblioteca) {
        this.biblioteca = biblioteca;
        initComponents();
        // Lê os livros armazenados no modelo Biblioteca e atualiza a tabela da tela.
        atualizarTabela();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfMatricula = new javax.swing.JTextField();
        jlAno = new javax.swing.JLabel();
        jtfContato = new javax.swing.JTextField();
        jlNome = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jlAutor = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMembros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Membros");

        jlAno.setText("Contato:");

        jtfContato.addActionListener(this::jtfContatoActionPerformed);

        jlNome.setText("Nome:");

        jlAutor.setText("Matrícula:");

        jbCadastrar.setText("Cadastrar membro");
        jbCadastrar.addActionListener(this::jbCadastrarActionPerformed);

        jbEditar.setText("Editar membro");
        jbEditar.addActionListener(this::jbEditarActionPerformed);

        jtMembros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtMembros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMembrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtMembros);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlAno)
                            .addComponent(jlAutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jtfMatricula)
                            .addComponent(jtfContato))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAno, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbEditar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfContatoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContatoActionPerformed

    // Valida os campos e cadastra um novo Membro na Biblioteca.
    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        String nome = jtfNome.getText().trim();
        String matricula = jtfMatricula.getText().trim();
        String contato = jtfContato.getText().trim();

        if (nome.isEmpty() || matricula.isEmpty() || contato.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }

        int proximoId = 1;
        for (Membro membro : biblioteca.getMembros()) {
            if (matricula.equalsIgnoreCase(membro.getMatricula())) {
                javax.swing.JOptionPane.showMessageDialog(this, "Essa matrícula já está cadastrada.");
                return;
            }
            proximoId = Math.max(proximoId, membro.getId() + 1);
        }

        // O modelo anterior exige e-mail no construtor; esta atividade pede contato.
        Membro membro = new Membro(proximoId, nome, "", contato);
        membro.setMatricula(matricula);
        biblioteca.cadastrarMembro(membro);

        atualizarTabela();
        jtfNome.setText("");
        jtfMatricula.setText("");
        jtfContato.setText("");

        javax.swing.JOptionPane.showMessageDialog(this, "Membro cadastrado com sucesso.");
    }//GEN-LAST:event_jbCadastrarActionPerformed
    
    // Atualiza os dados do membro selecionado na tabela.
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        // TODO add your handling code here:
        int linha = jtMembros.getSelectedRow();
        if (linha < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um membro na tabela.");
            return;
        }

        int linhaModelo = jtMembros.convertRowIndexToModel(linha);
        int id = (int) jtMembros.getModel().getValueAt(linhaModelo, 0);

        String nome = jtfNome.getText().trim();
        String matricula = jtfMatricula.getText().trim();
        String contato = jtfContato.getText().trim();

        if (nome.isEmpty() || matricula.isEmpty() || contato.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos.");
            return;
        }

        for (Membro outro : biblioteca.getMembros()) {
            if (outro.getId() != id
                    && matricula.equalsIgnoreCase(outro.getMatricula())) {
                javax.swing.JOptionPane.showMessageDialog(this, "Essa matrícula já pertence a outro membro.");
                return;
            }
        }

        Membro membro = biblioteca.buscarMembroPorId(id);
        if (membro == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Membro não encontrado.");
            return;
        }

        biblioteca.editarMembro(id, nome, membro.getEmail(), contato);
        membro.setMatricula(matricula);

        atualizarTabela();
        jtfNome.setText("");
        jtfMatricula.setText("");
        jtfContato.setText("");

        javax.swing.JOptionPane.showMessageDialog(this, "Membro atualizado com sucesso.");
    }//GEN-LAST:event_jbEditarActionPerformed
    
    // Ao clicar em uma linha da tabela, carrega os dados do membro nos campos
    // do formulário para permitir sua edição.
    private void jtMembrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMembrosMouseClicked
        // TODO add your handling code here:
        int linha = jtMembros.getSelectedRow();
        if (linha < 0) {
            return;
        }

        int linhaModelo = jtMembros.convertRowIndexToModel(linha);
        int id = (int) jtMembros.getModel().getValueAt(linhaModelo, 0);
        Membro membro = biblioteca.buscarMembroPorId(id);

        if (membro != null) {
            jtfNome.setText(membro.getNome());
            jtfMatricula.setText(membro.getMatricula());
            jtfContato.setText(membro.getTelefone());
        }
    }//GEN-LAST:event_jtMembrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMembros().setVisible(true));
    }
    
    /**
    * Atualiza a JTable com os registros armazenados na Biblioteca.
    * Cria as colunas e adiciona uma linha para cada registro do modelo.
    */
    private void atualizarTabela() {
        javax.swing.table.DefaultTableModel modelo =
            new javax.swing.table.DefaultTableModel(
                new Object[]{"ID", "Nome", "Matrícula", "Contato"}, 0
            ) {
                @Override
                public boolean isCellEditable(int linha, int coluna) {
                    return false;
                }
            };

        for (Membro membro : biblioteca.getMembros()) {
            modelo.addRow(new Object[]{
                membro.getId(),
                membro.getNome(),
                membro.getMatricula(),
                membro.getTelefone()
            });
        }

        jtMembros.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbEditar;
    private javax.swing.JLabel jlAno;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlNome;
    private javax.swing.JTable jtMembros;
    private javax.swing.JTextField jtfContato;
    private javax.swing.JTextField jtfMatricula;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
