/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Felipe Junior e Jhonathan Freitas
 */
import javax.swing.JOptionPane;
        
public class TelaEmprestimos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaEmprestimos.class.getName());
    private final Biblioteca biblioteca;
    
    /**
     * Creates new form TelaEmprestimos
     */
    public TelaEmprestimos() {
        this(new Biblioteca());
    }

    public TelaEmprestimos(Biblioteca biblioteca) {
        this.biblioteca = biblioteca;
        initComponents();
        setSize(460, 420);
        // Preenche as listas com livros disponíveis e membros cadastrados na Biblioteca.
        atualizarOpcoes();
        // Exibe na tabela os empréstimos ativos e encerrados registrados na Biblioteca.
        atualizarTabela();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbRealizar = new javax.swing.JButton();
        jbEncerrar = new javax.swing.JButton();
        jlLivro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmprestimos = new javax.swing.JTable();
        jlAutor = new javax.swing.JLabel();
        jcbLivro = new javax.swing.JComboBox<>();
        jcbMembro = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciamento de Empréstimos");
        setPreferredSize(new java.awt.Dimension(400, 434));

        jbRealizar.setText("Realizar empréstimo");
        jbRealizar.addActionListener(this::jbRealizarActionPerformed);

        jbEncerrar.setText("Encerrar empréstimo");
        jbEncerrar.addActionListener(this::jbEncerrarActionPerformed);

        jlLivro.setText("Livro:");

        jtEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtEmprestimos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEmprestimosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtEmprestimos);

        jlAutor.setText("Membro:");

        jcbMembro.addActionListener(this::jcbMembroActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbRealizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEncerrar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbMembro, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcbLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMembro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbRealizar)
                    .addComponent(jbEncerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Valida as seleções e registra na Biblioteca o empréstimo do livro ao membro.
    private void jbRealizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRealizarActionPerformed
        // TODO add your handling code here:
        if (jcbLivro.getSelectedItem() == null || jcbMembro.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Selecione um livro e um membro.");
            return;
        }

        String livroSelecionado = (String) jcbLivro.getSelectedItem();
        String membroSelecionado = (String) jcbMembro.getSelectedItem();

        int idLivro = Integer.parseInt(livroSelecionado.split(" - ", 2)[0]);
        int idMembro = Integer.parseInt(membroSelecionado.split(" - ", 2)[0]);

        int novoId = 1;
        for (Emprestimo emprestimo : biblioteca.getEmprestimos()) {
            novoId = Math.max(novoId, emprestimo.getId() + 1);
        }

        biblioteca.realizarEmprestimo(novoId, idLivro, idMembro);
        atualizarOpcoes();
        atualizarTabela();

        JOptionPane.showMessageDialog(this, "Empréstimo realizado com sucesso!");
    }//GEN-LAST:event_jbRealizarActionPerformed

    // Encerra o empréstimo selecionado na tabela e torna o livro disponível novamente.
    private void jbEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEncerrarActionPerformed
        // TODO add your handling code here:
        int linha = jtEmprestimos.getSelectedRow();
        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo na tabela.");
            return;
        }

        int linhaModelo = jtEmprestimos.convertRowIndexToModel(linha);
        int id = (int) jtEmprestimos.getModel().getValueAt(linhaModelo, 0);

        for (Emprestimo emprestimo : biblioteca.getEmprestimos()) {
            if (emprestimo.getId() == id && !emprestimo.isAtivo()) {
                JOptionPane.showMessageDialog(this, "Esse empréstimo já foi encerrado.");
                return;
            }
        }

        biblioteca.encerrarEmprestimo(id);
        atualizarOpcoes();
        atualizarTabela();

        JOptionPane.showMessageDialog(this, "Empréstimo encerrado com sucesso!");
    }//GEN-LAST:event_jbEncerrarActionPerformed

    private void jtEmprestimosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEmprestimosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtEmprestimosMouseClicked

    private void jcbMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMembroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbMembroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaEmprestimos().setVisible(true));
    }
    
    //Fazer as informações aparecer na tabela
    private void atualizarOpcoes() {
        jcbLivro.removeAllItems();
        jcbMembro.removeAllItems();

        for (Livro livro : biblioteca.getLivros()) {
            if (livro.getDisponivel()) {
                jcbLivro.addItem(livro.getId() + " - " + livro.getTitulo());
            }
        }

        for (Membro membro : biblioteca.getMembros()) {
            jcbMembro.addItem(membro.getId() + " - " + membro.getNome());
        }

        jcbLivro.setSelectedIndex(-1);
        jcbMembro.setSelectedIndex(-1);
    }
    
    /**
    * Atualiza a JTable com os registros armazenados na Biblioteca.
    * Cria as colunas e adiciona uma linha para cada registro do modelo.
    */
    private void atualizarTabela() {
        javax.swing.table.DefaultTableModel modelo =
            new javax.swing.table.DefaultTableModel(
                new Object[]{"ID", "Livro", "Membro", "Empréstimo", "Devolução", "Status"}, 0
            ) {
                @Override
                public boolean isCellEditable(int linha, int coluna) {
                    return false;
                }
            };

        for (Emprestimo emprestimo : biblioteca.getEmprestimos()) {
            modelo.addRow(new Object[]{
                emprestimo.getId(),
                emprestimo.getLivro().getTitulo(),
                emprestimo.getMembro().getNome(),
                emprestimo.getDataEmprestimo(),
                emprestimo.getDataDevolucao() == null
                    ? ""
                    : emprestimo.getDataDevolucao(),
                emprestimo.isAtivo() ? "Ativo" : "Encerrado"
            });
        }

        jtEmprestimos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEncerrar;
    private javax.swing.JButton jbRealizar;
    private javax.swing.JComboBox<String> jcbLivro;
    private javax.swing.JComboBox<String> jcbMembro;
    private javax.swing.JLabel jlAutor;
    private javax.swing.JLabel jlLivro;
    private javax.swing.JTable jtEmprestimos;
    // End of variables declaration//GEN-END:variables
}
